INSERT INTO RoleUser
Values
('Admin'),
('User');
go
INSERT INTO City
Values 
('Ha Noi'),
('Da Nang'),
('Ho Chi Minh');
go
INSERT INTO District
Values 
(1 , 'Ba Dinh'),
(1 , 'Hoan Kiem'),
(1 , 'Tay Ho'),
(1 , 'Long Bien'),
(1 , 'Cau Giay'),
(1 , 'Dong Da'),
(1 , 'Hai Ba Trung'),
(1 , 'Hoang Mai'),
(1 , 'Thanh Xuan'),
(1 , 'Soc Son'),
(2 , 'Lien Chieu'),
(2 , 'Thanh Khe'),
(2 , 'Hai Chau'),
(2 , 'Son Tra'),
(2 , 'Ngu Hanh Son'),
(2 , 'Cam Le'),
(2 , 'Hoa Vang'),
(3 , 'Hoc Mon'),
(3 , 'Cu Chi'),
(3 , 'Phu Nhuan'),
(3 , 'Tan Phu'),
(3 , 'Tan Binh'),
(3 , 'Go Vap'),
(3 , 'Binh Chanh'),
(3 , 'Nha Be'),
(3 , 'Can Gio'),
(3 , 'Binh Tan'),
(3 , 'Thu Duc');
go

INSERT INTO Ward
Values 
(1 , 'Cong Vi'),
(1 , 'Dien Bien'),
(1 , 'Doi Can'),
(1 , 'Giang Vo'),
(1 , 'Kim Ma'),
(1 , 'Lieu Giai'),
(1 , 'Ngoc Ha'),
(1 , 'Ngoc Khanh'),
(1 , 'Nguyen Trung Truc'),
(1 , 'Phuc Xa'),
(1 , 'Quan Thanh'),
(1 , 'Thanh Cong'),
(1 , 'Truc Bach'),
(1 , 'Vinh Phuc'),
(2 , 'Chuong Duong'),
(2 , 'Cua Dong'),
(2 , 'Cua Nam'),
(2 , 'Dong Xuan'),
(2 , 'Hang Bac'),
(2 , 'Hang Bai'),
(2 , 'Hang Bo'),
(2 , 'Hang Bong'),
(2 , 'Hang Buom'),
(2 , 'Hang Dao'),
(2 , 'Hang Gai'),
(2 , 'Hang Ma'),
(2 , 'Hang Trong'),
(2 , 'Ly Thai To'),
(2 , 'Phan Chu Trinh'),
(2 , 'Phuc Tan'),
(2 , 'Tran Hung Dao'),
(2 , 'Trang Tien'),
(3 , 'Buoi'),
(3 , 'Nhat Tan'),
(3 , 'Phu Thuong'),
(3 , 'Quang An'), 
(3 , 'Thuy Khue'),
(4 , 'Bo De'),
(4 , 'Cu Khoi'),
(4 , 'Duc Giang'),
(4 , 'Gia Thuy'),
(4 , 'Giang Bien'),
(5 , 'Dich Vong'),
(5 , 'Nghia Tan'),
(5 , 'Quan Hoa'),
(5 , 'Nghia Do'),
(5 , 'Yen Hoa'),
(6 , 'Quoc Tu Giam'),
(6 , 'Nam Dong'),
(6 , 'Tho Quan'),
(6 , 'Van Chuong'),
(6 , 'Van Mieu'),
(7 , 'Bach Khoa'),
(7 , 'Bach Dang'),
(7 , 'Nguyen Du'),
(7 , 'Thanh Luong'),
(7 , 'Thanh Nhan'),
(8 , 'Dai Kim'),
(8 , 'Dinh Cong'),
(8 , 'Giap Bat'),
(8 , 'Hoang Liet'),
(8 , 'Hoang Van Thu'),
(9 , 'Khuong Dinh'),
(9 , 'Thuong Dinh'),
(9 , 'Thanh Xuan Bac'),
(9 , 'Thanh Xuan Nam'),
(9 , 'Thanh Xuan Trung'),
(10 , 'Bac Phu'),
(10 , 'Bac Son'),
(10 , 'Kim Lu'),
(10 , 'Mai Dinh'),
(10 , 'Minh Phu'),
(10 , 'Thanh Xuan'),
(11 , 'Hoa Minh'),
(11 , 'Hoa Khanh Nam'),
(11 , 'Hoa Khanh Bac'),
(11 , 'Hoa Hiep Nam'),
(11 , 'Hoa Hiep Bac'),
(12 , 'Tan Chinh'),
(12 , 'Vinh Trung'),
(12 , 'Xuan Ha'),
(12 , 'Tam Thuan'),
(12 , 'Chinh Gian'),
(13 , 'Phuoc Ninh'),
(13 , 'Binh Thuan'),
(13 , 'Binh Hien'),
(13 , 'Hoa Cuong Nam'),
(13 , 'Hoa Cuong Bac'),
(14 , 'Tho Quang'),
(14 , 'Man Thai'),
(14 , 'Phuoc My'),
(14 , 'An Hai Dong'),
(14 , 'An Hai Bac'),
(15 , 'My An'),
(15 , 'Khue My'),
(15 , 'Hoa Hai'),
(15 , 'Hoa Quy'),
(16 , 'Khue Trung'),
(16 , 'Hoa Tho Dong'),
(16 , 'Hoa Tho Tay'),
(16 , 'Hoa An'),
(16 , 'Hoa Phat'),
(16 , 'Hoa Xuan'),
(17 , 'Hoa Chau'),
(17 , 'Hoa Tien'),
(17 , 'Hoa Phuoc'),
(17 , 'Hoa Phong'),
(17 , 'Hoa Nhon'),
(18 , 'Ba Diem'),
(18 , 'Xuan Thoi Son'),
(18 , 'Thoi Tam Thon'),
(18 , 'Tan Xuan'),
(18 , 'Tan Thoi Nhi'),
(19 , 'Tan Thanh Tay'),
(19 , 'Tan Thanh Dong'),
(19 , 'Binh My'),
(19 , 'Phu Hoa Dong'),
(19 , 'Phuoc Hiep'),
(20 , '1'),
(20 , '2'),
(20 , '3'),
(20 , '4'),
(20 , '5'),
(21 , 'Tan Son Nhi'),
(21 , 'Tay Thanh'),
(21 , 'Tan Quy'),
(21 , 'Tan Thanh'),
(21 , 'Phu Trung'),
(22 , '1'),
(22 , '2'),
(22 , '3'),
(22 , '4'),
(22 , '5'),
(23 , '3'),
(23 , '4'),
(23 , '5'),
(23 , '6'),
(23 , '7'),
(24 , 'Binh Chanh'),
(24 , 'Binh Hung'),
(24 , 'Binh Loi'),
(24 , 'Vinh Loc A'),
(24 , 'Vinh Loc B'),
(25 , 'Phuoc Kien'),
(25 , 'Phuoc Loc'),
(25 , 'Phu Xuan'),
(25 , 'Long Thoi'),
(25 , 'Hiep Phuoc'),
(26 , 'An Thoi Dong'),
(26 , 'Binh Khanh'),
(26 , 'Long Hoa'),
(26 , 'Ly Nhon'),
(26 , 'Tam Thon Hiep'),
(27 , 'My Thuan'),
(27 , 'Nguyen Van Thanh'),
(27 , 'Thanh Trung'),
(27 , 'Tan Thanh'),
(27 , 'Tan Hung'),
(28 , 'An Khanh'),
(28 , 'An Phu'),
(28 , 'Binh Trung'),
(28 , 'Hiep Binh'),
(28 , 'Linh Xuan');
