//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunshine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Plans = new HashSet<Plan>();
            this.Plans1 = new HashSet<Plan>();
            this.Plans2 = new HashSet<Plan>();
            this.Plans3 = new HashSet<Plan>();
            this.Posts = new HashSet<Post>();
            this.Posts1 = new HashSet<Post>();
            this.Posts2 = new HashSet<Post>();
            this.Posts3 = new HashSet<Post>();
            this.Users = new HashSet<User>();
            this.Users1 = new HashSet<User>();
            this.Users2 = new HashSet<User>();
            this.Users3 = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int IdRole { get; set; }
        public string NameAddress { get; set; }
    
        public virtual RoleAddress RoleAddress { get; set; }
        public virtual ICollection<Plan> Plans { get; set; }
        public virtual ICollection<Plan> Plans1 { get; set; }
        public virtual ICollection<Plan> Plans2 { get; set; }
        public virtual ICollection<Plan> Plans3 { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Post> Posts1 { get; set; }
        public virtual ICollection<Post> Posts2 { get; set; }
        public virtual ICollection<Post> Posts3 { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<User> Users1 { get; set; }
        public virtual ICollection<User> Users2 { get; set; }
        public virtual ICollection<User> Users3 { get; set; }
    }
}
