//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunshine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUser
    {
        public RoleUser()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string NameRole { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
