//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sunshine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Posts = new HashSet<Post>();
            this.Sponsors = new HashSet<Sponsor>();
        }
    
        public int Id { get; set; }
        public int IdRole { get; set; }
        public string NameUser { get; set; }
        public string Phone { get; set; }
        public bool Gender { get; set; }
        public string Street { get; set; }
        public int IdWard { get; set; }
        public int IdDistrict { get; set; }
        public int IdCity { get; set; }
        public string PasswordUser { get; set; }
    
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual RoleUser RoleUser { get; set; }
        public virtual ICollection<Sponsor> Sponsors { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
